services:
  abec.dev:
    container_name: abec-dev
    image: d.espacebyte.net/berto/abec.io:dev
    ports:
      - '8080:80'
    environment:
      TZ: America/New_York
      DEBUG: true
      DEV_MODE: true
      LOG: /logs
      X_FRAME_ORIGINS: '*.dndbeyond.com'
      DB_DIR: /db
      NO_PULL: true
    volumes:
      - ./dockerApp/db/:/db:rw
      - ./dockerApp/logs/:/logs:rw
      # Optional, just saves startup time
      - ./:/repo:ro
